# Climate Coding Challenge

Climate change is impacting the way people live around the world

## Step 1: Wrangle your data

### Step 1A: Load Python packages
Python **packages** let you use code written by experts around the world.

Because Python is open source, lots of different people and organizations can contribute (including you!). Many contributions are in the form of **packages** which do not come with a standard Python download.

**Learn more about using Python packages:** How do you find and use packages? What is the difference between installing and importing packages? When do you need to do each one? <a
href="https://www.earthdatascience.org/courses/intro-to-earth-data-science/python-code-fundamentals/use-python-packages/">This article on Python packages</a> will walk you through the basics.</p></div></div>

In the cell below, someone was trying to import the **pandas package**, which helps us to work with **tabular data** such as comma-separated value or csv files (e.g. data with rows and columns like a spreadsheet). But something’s wrong!

In [1]:
### import libraries
import earthpy ### manage local data
import pandas as pd

<link rel="stylesheet" type="text/css" href="./assets/styles.css"><div class="callout callout-style-default callout-titled callout-task"><div class="callout-header"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-title-container flex-fill">Try It: Import packages</div></div><div class="callout-body-container callout-body"><ol type="1">
<li>Correct the typo in the chunk above to properly import the pandas package under
its <strong>alias</strong> pd.</li>
<li>Add a descriptive comment next to the pandas package explaining what it does. You can add comments using the # symbol, just like we did your you for the earthpy package in the first line of the code chunk.</li>
<li>Run the cell to import the libraries you’ll need for this
workflow.</li>
</ol></div></div>

> **Warning**
>
> Make sure to run your code in the right **environment** to avoid
> import errors!
>
> We’ve created a coding **environment** for you to use that already has
> all the software and packages you will need! When you try to run some
> code, you may be prompted to select a **kernel**. The **kernel**
> refers to the version of Python you are using. You should use the
> **base** kernel, which should be the default option for you.

### Step 1B: Download the practice data

Next, you'll download some climate data from Boulder, CO to practice with. The data will come in comma-separate value, or CSV format.

You can learn more about tabular data and CSV files <a
href="https://earthdatascience.org/courses/intro-to-earth-data-science/file-formats/use-text-files/">in this article on text files</a>.</p></div></div>

Here's some starter code to access the data we'll use for this assignment:

In [2]:
### define project name
project_name = 'Boulder Climate'

### set up project folders
project = earthpy.Project(
    project_name,
    dirname = 'workspaces/01-climate-fall-template/data/boulder_climate')

### download data
project.get_data()

### check where the data ended up
project.project_dir

PosixPath('/home/jovyan/.local/share/earth-analytics/workspaces/01-climate-fall-template/data/boulder_climate')

<link rel="stylesheet" type="text/css" href="./assets/styles.css"><div class="callout callout-style-default callout-titled callout-task"><div class="callout-header"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-title-container flex-fill">Try it yourself:</div></div><div class="callout-body-container callout-body"><ol type="1">
<li>Replace <code>Project Name Here</code> with the actual project name,
<span data-__quarto_custom="true" data-__quarto_custom_type="Shortcode"
data-__quarto_custom_context="Inline"
data-__quarto_custom_id="5"></span>.</li>
<li>Replace <code>data-folder-name-here</code> with a
<em>descriptive</em> name for your data folder.</li>
<li>Run the cell. Can you find the data on your computer?</li>
</ol></div></div>

You can make sure that your data are loaded using the `bash` programming language, either in your terminal or here in your Jupyter notebook (the `!` tells the computer to use the current bash process, and the `{}` indicates to use a Python variable):

In [3]:
!ls "{project.project_dir}"

ncei-climate-boulder.csv

### Step 1C: Import data to Python

The `pandas` library you imported can download data from the internet directly into a type of Python **object** called a `DataFrame`. In the code cell below, you can see an attempt to do just this. But there are some problems…

In [4]:
# Load climate data from NCEI
pd.read_csv(
    project.project_dir / 'ncei-climate-boulder.csv'
    )

             DATE      STATION  TOBS
0      1893-10-01  USC00050848   NaN
1      1893-10-02  USC00050848   NaN
2      1893-10-03  USC00050848   NaN
3      1893-10-04  USC00050848   NaN
4      1893-10-05  USC00050848   NaN
...           ...          ...   ...
45966  2023-09-26  USC00050848  74.0
45967  2023-09-27  USC00050848  69.0
45968  2023-09-28  USC00050848  73.0
45969  2023-09-29  USC00050848  66.0
45970  2023-09-30  USC00050848  78.0

[45971 rows x 3 columns]

<link rel="stylesheet" type="text/css" href="./assets/styles.css"><div class="callout callout-style-default callout-titled callout-task"><div class="callout-header"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-title-container flex-fill">Try it yourself:</div></div><div class="callout-body-container callout-body"><ol type="1">
<li><p>Make any changes needed to get this code to run. HINT: The <code>filename.csv</code> isn’t correct - you need to replace it with the name of the file you downloaded! See if you can find where the data downloaded to.</p></li>
<li><p>The <code>pd.read_csv()</code> function isn’t formatting the data 100% correctly. Modify the code to include the following additional parameters, making sure to put a comma (<code>,</code>) in-between each parameter:</p>
<ul>
<li><code>index_col='DATE'</code> – this sets the <code>DATE</code> column as the index. Needed for subsetting and resampling later on</li>
<li><code>parse_dates=True</code> – this lets <code>python</code> know that you are working with time-series data, and values in the indexed column are <strong>date time objects</strong></li>
<li><code>na_values=['NaN']</code> – this lets <code>python</code> know how to handle missing values</li>
</ul></li>
<li><p>We can’t get the data back later on because it isn’t saved in a <strong>variable</strong>. In other words, we need to give the url a <strong>name</strong> so that we can request in from Python later (sadly, Python has no ‘hey what was that thingy I typed yesterday?’ function). Make sure to use an <strong>expressive variable name</strong> so you remember what it is later on!</p></li>
</ol></div></div>

> **Tip**
>
> Check out the `type()` function below - you can use it to check that
> your data is now in `DataFrame` type object.

**Names/variables in Python:** One of the most common challenges for new programmers is making sure that your results are stored so you can use them again. In Python, this is called <strong>naming</strong>, or saving a <strong>variable</strong>. Learn more in the <a href="https://www.earthdatascience.org/courses/intro-to-earth-data-science/python-code-fundamentals/get-started-using-python/variables/">lesson on variables in Python.</p></div></div>

In [5]:
climate_df = pd.read_csv(
    project.project_dir / 'ncei-climate-boulder.csv',

    ### tell python which column to use as index
    index_col = 'DATE', 

    ### python to treat date as date
    parse_dates= True)

In [6]:
### check that data was imported into a pandas DataFrame
type(climate_df)

pandas.core.frame.DataFrame

### Step 1D: Clean up your `DataFrame`

<link rel="stylesheet" type="text/css" href="./assets/styles.css"><div class="callout callout-style-default callout-titled callout-task"><div class="callout-header"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-title-container flex-fill"></div></div><div class="callout-body-container callout-body"><p>You can use <strong>double brackets</strong> (<code>[[</code> and
<code>]]</code>) to select only the columns that you want from your
<code>DataFrame</code>:</p>
<ol type="1">
<li>Change <code>some_column_name</code> to the Temperature column
name.</li>
<li>Put quotes around your column name so Python interprets it as text
and not a variable name.</li>
<li>Clean up the code by using <strong>descriptive
comments</strong>.</li>
</ol></div></div>

In [7]:
### insert descriptive comment here
temp_df = climate_df[['TOBS']]
temp_df

            TOBS
DATE
1893-10-01   NaN
1893-10-02   NaN
1893-10-03   NaN
1893-10-04   NaN
1893-10-05   NaN
...          ...
2023-09-26  74.0
2023-09-27  69.0
2023-09-28  73.0
2023-09-29  66.0
2023-09-30  78.0

[45971 rows x 1 columns]

# Wrap up Steps 1A-1D

Don’t forget to store your variables so you can use them in other notebooks! Replace `var1` and `var2` with the variable you want to save, separated by spaces.

In [8]:
%store climate_df temp_df

Stored 'climate_df' (DataFrame)
Stored 'temp_df' (DataFrame)

Finally, be sure to `Restart` and `Run all` to make sure your notebook
works all the way through!